### ISSUE TITLE
请教polybar的字体

### ISSUE THREAD

**Issue by grayguest** [guyueshui/dotfiles#1]
请问mpd module所用的字体是`font-7 = Spectral:size=12;0`吧，我看mpd用得字体编号是`-font = 8`。
我电脑里面没这个字体，然后下载安装完后它不是中文字体吧？
https://fonts.google.com/specimen/Spectral?preview.text_type=custom&preview.text=#standard-styles
这里面预览的时候就不能预览中文。

但是我看作者你的可以显示中文歌曲名，莫非用得不是这个字体？

**Comment by guyueshui** [comment]
> 请问mpd module所用的字体是`font-7 = Spectral:size=12;0`吧，我看mpd用得字体编号是`-font = 8`。 我电脑里面没这个字体，然后下载安装完后它不是中文字体吧？ https://fonts.google.com/specimen/Spectral?preview.text_type=custom&preview.text=#standard-styles 这里面预览的时候就不能预览中文。
> 
> 但是我看作者你的可以显示中文歌曲名，莫非用得不是这个字体？

font列表里有文泉驿微米黑，应该是fallback到这个字体了。试了下去掉这个字体，中文就显示不出来了。抱歉刚看到这个issue 🤦
